baseURL: https://simonbaird.github.io/catpopins

languageCode: en-us
title: Cat Pop-ins

theme: hugo-split-theme

params:
  author: Aoife Austin
  description: todo

  visual:
    image:
      enable: true
      file: images/splash.png
      position: center center

  links:
    - list1:
        heading: Services
        link:
          - text: Cat sitting
            url: cat-sitting
          - text: Photography
            url: photography

    - list2:
        heading: About
        link:
          - text: Testimonials
            url: testimonials
          - text: Pricing
            url: pricing

    - list3:
        heading: Social
        link:
          - text: Instagram
            url: '#'
          - text: Facebook
            url: '#'
